# ov50 Linux/OSX build - courtesy to https://github.com/seandepagnier
language: cpp

matrix:
  include:
    - dist: focal
      compiler: gcc
    - os: osx
      osx_image: xcode11.3
      compiler: clang

install:

    - if [[ "$TRAVIS_OS_NAME" == "linux" ]];
      then
        sudo apt-get -qq update;
        sudo apt-get install libwxbase3.0-0v5 libwxbase3.0-dev wx-common;
        sudo apt-get install libwxgtk3.0-gtk3-0v5 libwxgtk3.0-gtk3-dev;
        sudo apt-get install libwxgtk-webview3.0-gtk3-0v5 libwxgtk-webview3.0-gtk3-dev;
        sudo apt-get install libgps-dev libglu1-mesa-dev libgtk2.0-dev libbz2-dev libtinyxml-dev;
        sudo apt-get install libexpat1-dev libcairo2-dev;
        sudo apt-get install rpm;
      fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]];
      then
        brew install cairo libexif xz libarchive;
        curl -o wx312B_opencpn50_macos109.tar.xz https://download.opencpn.org/s/rwoCNGzx6G34tbC/download;
        tar xJf wx312B_opencpn50_macos109.tar.xz -C /tmp;
        export PATH="/usr/local/opt/gettext/bin:$PATH";
        echo 'export PATH="/usr/local/opt/gettext/bin:$PATH"' >> ~/.bash_profile;
        curl -o Packages.dmg https://download.opencpn.org/s/SneCR3z9XM3aRc6/download;
        hdiutil attach Packages.dmg;
        sudo installer -pkg "/Volumes/Packages 1.2.5/Install Packages.pkg" -target "/";
      fi

script:
  - if [[ "${COVERITY_SCAN_BRANCH}" == 1 ]];
    then
      echo "Don't build on coverty_scan branch.";
      exit 0;
    fi
  - mkdir build && cd build
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]];
    then
       cmake -DCMAKE_BUILD_TYPE=Release ../ && make -sj2 package;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];
    then
        cmake -DwxWidgets_CONFIG_EXECUTABLE=/tmp/wx312B_opencpn50_macos109/bin/wx-config -DwxWidgets_CONFIG_OPTIONS="--prefix=/tmp/wx312B_opencpn50_macos109" -DCMAKE_INSTALL_PREFIX=/tmp/opencpn -DCMAKE_OSX_DEPLOYMENT_TARGET=10.14 .. && make -sj2 && make create-pkg;
     fi
  - ctest -j2
  - ls -l;

notifications:
  email: false
git:
  depth: 10
before_install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-9" CC="gcc-9"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-9
    - g++-9
deploy:
- provider: releases
  api_key:
    secure: "nx4vqgIxFQ/EWo1K8gUoKLpAOZEdlD5HRp+X2un7f61ydLpJ160JwrfojlzROnG+sZsbqdcEnGqqP+Kb0UeDPqZTdCJNPIvqruntJs9l3pfq2PxnWqdvaZapxNiBZfotyyF16p9qYQHPNgPqLqgiOzbCvEBRPp580lRUmHjDUsKPS9lCahfKNOm0bqc6KmOQCkk3CM8x8YLq7UFt1hCnb35jBNskTB+ePlMfUwShb2E7EMZR/X4BER/IVphV+ovW/SRI3fKVZOQBpednpOcDRFsRp5CQQaZPQ5SuQQwqrDTX6fgzE0zqSyhLaumjccBgydviId8u4wjlfe4KhfXmMZIUoOUiyib89XBkMVHqDQLF24fN3ibr3kVDYeggaxqXEKppw9Dx4nbXHf1qMn9hCqWxrnGIUFySMtbO/u8OGbhSsQ/qQlyvHnEbpk9NFtpOzj6LomRYqG1vlIMKGEm3eh0r6g4mae3ZhROZvP1lAeA8ZjhNftanywCL2GsXQCWDsbyUd2u5akvcGG4D25t4Bx/cj4Z80gtfGXuNEZFlywP3R0NPls9C5dpYOhV5Zqd5wyEmYLosXSbRnfylBY7gNSI9rxacrulfNInZvCc/o9Fr+vT7pdMgcEi65zIkT8B0nHhhqzFISsS98cIiEY+J/c9qf5yBrcULOm9R8X3SMzI="
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/build/*.{deb,rpm,dmg,txz,pkg,pkg.tar.xz}"
  skip_cleanup: true
  on:
    repo: canne/dashboard_tactics_pi
    tags: true
    all_branches: true
    
