clone_folder: c:\project\dashboard_tactics_pi
shallow_clone: true
image:
- Visual Studio 2017

platform: 
# - x64
- Win32

configuration: Release
test: OFF

environment:
  OCPN_TARGET: MSVC

install:
  - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat'

  # sent environment variables for wxWidgets
  - set WXWIN=C:\wxWidgets-3.1.2
  - set wxWidgets_ROOT_DIR=%WXWIN%
  - set wxWidgets_LIB_DIR=%WXWIN%\lib\vc_dll
  - set wxWidgets_LIBRARIES=%wxWidgets_LIB_DIR%
  - set wxWidgets_INCLUDE_DIRS=%WXWIN%\include
  - cmd: SET PATH=%PATH%;%WXWIN%;%wxWidgets_LIB_DIR%;C:\Program Files (x86)\Poedit\Gettexttools\bin;

  # install dependencies:
  - choco install poedit
  - choco install git
  
  - ps: Start-FileDownload http://opencpn.navnux.org/build_deps/nsis-3.04-setup.exe
  - cmd: nsis-3.04-setup.exe /S

  # Download and unzip wxwidgets
  - ps: Start-FileDownload http://opencpn.navnux.org/build_deps/wxWidgets-3.1.2.7z
  - cmd: 7z x wxwidgets-3.1.2.7z -o%WXWIN% > null

  # some debugging information
  - set

before_build:
  - cd c:\project\dashboard_tactics_pi
  - mkdir build
  - cd build
  - ps: Start-FileDownload https://github.com/canne/dashboard_pi/releases/download/0.0.1/opencpn.lib
  - cmake -T v141 ..

build_script:
  - cmake --build . --target package --config Release

test_script:
  - cmd: ctest -j2
    
artifacts:
  - path: 'build\*.exe'
    name: installer

deploy:
  description: 'release created by AppVeyor CI'
  provider: GitHub
  auth_token:
    secure: TlzWWbLC1CFCpSHQIFCIxdZhRQjLRZq+ylg578A6I/MH9UxtKcbi5IdnZf8C1/wY
  artifact: installer
  draft: true
  prerelease: true
  tag: $(APPVEYOR_REPO_TAG_NAME)
  on:
    appveyor_repo_tag: true # deploy on tag push only
    configuration: Release  # Debug contains non-redist MS DLLs
